services:
  brain-ai-vector-store:
    container_name: tuRevistaDeVideojuegos
    image: "pgvector/pgvector:pg17"
    volumes:
      - ./postgres-dev-data/17/data:/var/lib/postgresql/data
    ports:
      - "5500:5432"
    expose:
      - "5500"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: always
    environment:
      POSTGRES_DB: tuRevistaDeVideojuegos
      POSTGRES_USER: postgres    #${TUREVISTADEVIDEOJUEGOS_USERNAME:-postgres}
      POSTGRES_PASSWORD: postgres    #${TUREVISTADEVIDEOJUEGOS_PASSWORD:-postgres}